In [2]:
import numpy as np # 导入numpy，取别名为np

```python
numpy.array(): 创建一个数组，类型为numpy.ndarray，例如：
    arr = numpy.array()
array.dim: 输出数据的维度信息
```

In [3]:
data1 = np.array(
    5
) # 创建一个 0维 的ndarray
print(f"data1: {data1}, type: {type(data1)}, dtype: {data1.ndim}") # arr.ndim： 输出数据的维度

data1: 5, type: <class 'numpy.ndarray'>, dtype: 0


In [4]:
data2 = np.array([
    5,
]) # 创建一个 1维 的 ndarray
print(f"data2: {data2}, type: {type(data2)}, dtype: {data2.ndim}")

data2: [5], type: <class 'numpy.ndarray'>, dtype: 1


In [5]:
data3 = np.array([
    [1, 2], [2, 3],
]) # 创建一个 2维 的 ndarray
print(f"data3: {data3}, type: {type(data3)}, dtype: {data3.ndim}")

data3: [[1 2]
 [2 3]], type: <class 'numpy.ndarray'>, dtype: 2


In [6]:
data4 = np.array([
    [[1, 2, 3], [2, 3, 4]],
]) # 创建一个 3维 的 ndarray
print(f"data4: {data4}, type: {type(data4)}, dtype: {data4.ndim}")

data4: [[[1 2 3]
  [2 3 4]]], type: <class 'numpy.ndarray'>, dtype: 3


```python

关于ndarray同质性的问题：
当创建一个ndarray：
arr = numpy.array([
        1,
        "hello",
])
结果 可以创建成功，但是会自动做同质化数据转换，例如：
- 数字 + 字符串 -> 字符串
- 整数 + 浮点数 -> 浮点数
```

In [7]:
data5 = np.array([
    1,
    "hello",
])
print(f"data5: {data5}, type: {type(data5)}, dtype: {data5.ndim}")

data5: ['1' 'hello'], type: <class 'numpy.ndarray'>, dtype: 1


In [8]:
data6 = np.array([
    1,
    2.3,
])
print(f"data6: {data6}, type: {type(data6)}, dtype: {data6.ndim}")

data6: [1.  2.3], type: <class 'numpy.ndarray'>, dtype: 1


ndarray的属性:
- 1，shape： 数组的形状，包括行数、列数等
- 2， ndim：数组的维度数量
- 3， size：数组中总的元素个数
- 4， dtype： 元素类型

In [9]:
print(f"data6.shape: {data6.shape}, data6.ndim: {data6.ndim}, data6.size: {data6.size}, data6.dtype: {data6.dtype}")

data6.shape: (2,), data6.ndim: 1, data6.size: 2, data6.dtype: float64


| <center>用途</center>               | <center>方法</center>                                                                 |
|--------------------|----------------------------------------------------------------------|
| <center>基础构造</center>           |<center> `numpy.array()`、 `numpy.copy()`</center>                                             |
| <center>预定义形状填充</center>     |<center>`numpy.zeros()`、 `numpy.ones()`、 `numpy.empty()`、 `numpy.full()`</center>                    |
| <center>基于数值范围生成</center>   |<center>`numpy.arange()` 、`numpy.linspace()`、 `numpy.logspace()`</center>                        |
| <center>特殊矩阵生成</center>       |<center>`numpy.eye()`、 `numpy.diag()`</center>                                               |
| <center>随机数组生成</center>       |<center>`numpy.random.rand()`、 `numpy.random.randn()` 、`numpy.random.randint()`</center>         |
| <center>高级构造方法</center>       |<center>`numpy.array()`、 `numpy.loadtxt()`、 `numpy.fromfunction()`</center>                      |
|<center>基于已知数组创建</center>    |<center>`numpy.zeros_like()`、`numpy.ones_like()`、`numpy.empty_like()`、`numpy.full_like()`</center>        |

In [10]:
new1 = np.array([1,2,3])
print(f"new1: {new1}")

list1 = np.array(new1, dtype=np.float64)
print(list1, list1.dtype, list1.ndim, sep="\n")

new1: [1 2 3]
[1. 2. 3.]
float64
1


In [11]:
list2 = np.zeros([2, ], dtype=np.int64) # 创建一维数组，只需要填入个数即可
print(list2, list2.dtype, list2.ndim, sep="\n")

[0 0]
int64
1


In [12]:
new2 = np.copy(new1) # copy：复制相关的数组到新数组
new2

array([1, 2, 3])

In [13]:
new3 = np.zeros([2, 3], dtype=np.int64) # 创建两行三列的 全零 数组，可以指定类型，默认 np.float64
print(new3, new3.dtype, new3.ndim, sep="\n")

[[0 0 0]
 [0 0 0]]
int64
2


In [14]:
new4 = np.ones([2, 3]) # 创建两行三列的 全1 数组，dtype=np.float64
print(new4, new4.dtype, new4.ndim, sep="\n")

[[1. 1. 1.]
 [1. 1. 1.]]
float64
2


In [15]:
new5 = np.empty([2, 3]) # 创建两行三列的 未初始化的随机值的 数组
print(new5, new5.dtype, new5.ndim, sep="\n")

[[1. 1. 1.]
 [1. 1. 1.]]
float64
2


In [16]:
new5 = np.zeros([10, ]) # 创建1维 全0 数组
print(new5, new5.dtype, new5.ndim, sep="\n")

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
float64
1


In [17]:
new6 = np.full([3, 4], 2025) # 指定形状和填充值的数组创建
print(new6, new6.dtype, new6.ndim, sep="\n")

[[2025 2025 2025 2025]
 [2025 2025 2025 2025]
 [2025 2025 2025 2025]]
int64
2


In [18]:
new7 = np.zeros_like(new6) # 创建一个和已知数组形状相似的全零数组
print(new7, new7.dtype, new7.ndim, sep="\n")

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
int64
2


In [19]:
new8 = np.arange(1, 10, 2) # 创建一个指定起始范围(左闭右开)和步长的数组
print(new8, new8.dtype, new8.ndim, sep="\n")

[1 3 5 7 9]
int64
1


In [20]:
new9 = np.linspace(1, 10, 5) # 指定生成等间隔的序列，[起始点， 结束点， 数据个数]
print(new9, new9.dtype, new9.ndim, new9.size, sep="\n")

[ 1.    3.25  5.5   7.75 10.  ]
float64
1
5


In [21]:
new10 = np.logspace(1, 5, 5, base=2) # 对数间隔数列，指定开始点和结束点以及需要的个数，指定基数base
print(new10, new10.dtype, new10.ndim, new10.size, sep="\n")

[ 2.  4.  8. 16. 32.]
float64
1
5


In [22]:
new11 = np.eye(5, dtype=np.int64) # 单位矩阵的构造
print(new11, new11.dtype, new11.ndim, new11.size, sep="\n")

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
int64
2
25


In [23]:
new12 = np.diag([1,2,3,4]) # 创建一个主对角线上元素指定、其余部分为零的矩阵
print(new12, new12.dtype, new12.ndim, new12.size, sep="\n")

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
int64
2
16


In [24]:
new13 = np.random.rand(2, 3) # 创建一个在0~1之间均匀分布的随机数组
print(new13, new13.dtype, new13.ndim, new13.size, sep="\n")

[[0.64859002 0.30610052 0.37857958]
 [0.77388519 0.09495973 0.11559632]]
float64
2
6


In [25]:
new14 = np.random.uniform(3, 6, [3, 3]) # 生成一个指定形状和指定区间范围的均匀分布的随机数组
print(new14, new14.dtype, new14.ndim, new14.size, sep="\n")

[[3.66921361 5.04148244 5.49994867]
 [4.27440854 5.82238601 3.1937516 ]
 [5.52268374 3.59034965 5.24874464]]
float64
2
9


In [26]:
new15 = np.random.randint(3, 6, [3, 3]) # 生成一个指定形状和指定区间范围的均匀分布的整型随机数组
print(new15, new15.dtype, new15.ndim, new15.size, sep="\n")

[[3 3 4]
 [3 5 3]
 [3 5 5]]
int32
2
9


In [27]:
new16 = np.random.randn(3, 6) # 生成一个指定形状和指定区间范围的正态分布的整型随机数组，高斯分布，生成在(-3, 3)之间的
print(new16, new16.dtype, new16.ndim, new16.size, sep="\n")

[[ 0.38050322  0.70593953  0.50624302  2.23361336  0.15422499  0.05715397]
 [ 0.24022779 -0.9746798  -0.78051862 -0.07282461 -1.37936087  0.60484925]
 [-0.74554523  0.04338461  1.72413962  0.41734556 -2.12078189  0.43472093]]
float64
2
18


In [28]:
np.random.seed(20) # 设置随机种子
new17 = np.random.randn(3, 6) # 生成一个指定形状和指定区间范围的正态分布的整型随机数组，高斯分布，生成在(-3, 3)之间的
print(new17, new17.dtype, new17.ndim, new17.size, sep="\n")

[[ 0.88389311  0.19586502  0.35753652 -2.34326191 -1.08483259  0.55969629]
 [ 0.93946935 -0.97848104  0.50309684  0.40641447  0.32346101 -0.49341088]
 [-0.79201679 -0.84236793 -1.27950266  0.24571517 -0.0441948   1.56763255]]
float64
2
18


In [29]:
print(f"new17[2][3]: {new17[2][3]}\n")
print(f"通过位置切片索引：new17[:2]:\n {new17[:2]}\n") # 位置索引依旧左闭右开

# 通过slice函数进行索引，左闭右开，slice(start, end, step)
print(f"通过slice函数索引：new17[:2]:\n {new17[slice(0,2)]}\n")

print(f"new17[2][:3]: {new17[2][:3]}\n")
print(f"new17第四列：{new17[:, 3]}") # 获取某一列
print(f"new17第二行：{new17[1]}")

new17[2][3]: 0.24571516951123312

通过位置切片索引：new17[:2]:
 [[ 0.88389311  0.19586502  0.35753652 -2.34326191 -1.08483259  0.55969629]
 [ 0.93946935 -0.97848104  0.50309684  0.40641447  0.32346101 -0.49341088]]

通过slice函数索引：new17[:2]:
 [[ 0.88389311  0.19586502  0.35753652 -2.34326191 -1.08483259  0.55969629]
 [ 0.93946935 -0.97848104  0.50309684  0.40641447  0.32346101 -0.49341088]]

new17[2][:3]: [-0.79201679 -0.84236793 -1.27950266]

new17第四列：[-2.34326191  0.40641447  0.24571517]
new17第二行：[ 0.93946935 -0.97848104  0.50309684  0.40641447  0.32346101 -0.49341088]


In [30]:
print(f"new17[2]: {new17[2]}\n")

# 传入的索引类型为bool，筛选对应维度中满足bool条件的值，可以通过 &、 | 将多条件并联
print(f"new17[2]中所有小于0的值: {new17[2][new17[2]<0]}\n")
print(f"new17[2]中所有小于0且大于-1的值: {new17[2][(new17[2] < 0) & (new17[2] > -1)]}\n")

new17[2]: [-0.79201679 -0.84236793 -1.27950266  0.24571517 -0.0441948   1.56763255]

new17[2]中所有小于0的值: [-0.79201679 -0.84236793 -1.27950266 -0.0441948 ]

new17[2]中所有小于0且大于-1的值: [-0.79201679 -0.84236793 -0.0441948 ]



In [31]:
np.random.seed(200)

In [32]:
arr1 = np.random.randint(1, 100, (2, 4))
arr2 = np.random.randint(2, 200, (2, 4))
arr3 = np.random.randint(3, 300, (3, 4))
print(f"arr1:\n {arr1}")
print(f"arr2:\n {arr2}")
print(f"arr3:\n {arr3}")

arr1:
 [[27 17 69 43]
 [56 77 80 90]]
arr2:
 [[ 16 187  91 141]
 [136  44  58   3]]
arr3:
 [[ 10  54 204 146]
 [132 241 282  88]
 [266 275 294 247]]


In [33]:
print(f"arr1+arr2:\n {arr1 + arr2}")
print(f"arr1-arr2:\n {arr1 - arr2}")
print(f"arr1xarr2:\n {arr1 * arr2}")
print(f"arr1/arr2:\n {arr1 / arr2}")

arr1+arr2:
 [[ 43 204 160 184]
 [192 121 138  93]]
arr1-arr2:
 [[  11 -170  -22  -98]
 [ -80   33   22   87]]
arr1xarr2:
 [[ 432 3179 6279 6063]
 [7616 3388 4640  270]]
arr1/arr2:
 [[ 1.6875      0.09090909  0.75824176  0.30496454]
 [ 0.41176471  1.75        1.37931034 30.        ]]


In [34]:
print(f"arr3:\n {arr3}")
print(f"arr3+5:\n {arr3+5}")
print(f"arr3*5:\n {arr3*5}")

arr3:
 [[ 10  54 204 146]
 [132 241 282  88]
 [266 275 294 247]]
arr3+5:
 [[ 15  59 209 151]
 [137 246 287  93]
 [271 280 299 252]]
arr3*5:
 [[  50  270 1020  730]
 [ 660 1205 1410  440]
 [1330 1375 1470 1235]]


In [35]:
arr4 = np.array([1,2,3])
arr5 = np.array([[4], [5], [6]])
print(f"arr4:\n {arr4}")
print(f"arr5:\n {arr5}")
print(f"arr4+arr5:\n {arr4 + arr5}")

arr4:
 [1 2 3]
arr5:
 [[4]
 [5]
 [6]]
arr4+arr5:
 [[5 6 7]
 [6 7 8]
 [7 8 9]]


In [36]:
arr6 = np.random.randint(1,10,(3, 3))
arr7 = np.random.randint(1,10,(3, 3))
print(f"arr6:\n {arr6}")
print(f"arr7:\n {arr7}")
print(f"arr1@arr2:\n {arr6 @ arr7}")

arr6:
 [[1 5 3]
 [6 3 5]
 [1 4 8]]
arr7:
 [[9 9 4]
 [2 9 1]
 [5 7 4]]
arr1@arr2:
 [[ 34  75  21]
 [ 85 116  47]
 [ 57 101  40]]


## Numpy中的常用函数
| 基本数学            | 统计运算            | 比较与逻辑运算        | 数组操作              |
|---------------------|---------------------|-----------------------|-----------------------|
| `np.sqrt(x)`        | `np.sum(x)`         | `np.greater(a, b)`    | `np.concatenate((a, b))` |
| `np.exp(x)`         | `np.mean(x)`        | `np.less(a, b)`       | `np.split(x, indices)`  |
| `np.log(x)`         | `np.median(x)`      | `np.equal(a, b)`      | `np.reshape(x, shape)`  |
| `np.sin(x)`         | `np.std(x)`         | `np.logical_and(a, b)`| `np.copy(x)`           |
| `np.abs(x)`         | `np.var(x)`         | `np.where(condition, x, y)` | `np.isnan(x)`      |
| `np.power(a, b)`    | `np.min(x)` / `np.max(x)` | `np.unique(x)`   | `np.sort(x)`           |
| `np.round(x, n)`    | `np.percentile(x, q)` | `np.in1d(a, b)`    | `x.sort()`             |
|                     |                     |                       | `np.argsort(x)`        |
|                     |                     |                       | `np.lexsort(keys)`     |

In [37]:
print(np.round([1.2, 3.4, 4.5, 4.51, 5.41])) # “四舍五入”机制，小数部分大于 0.5 才进行“入”的操作，否则进行“舍”的操作

[1. 3. 4. 5. 5.]


In [38]:
print(np.ceil([1.2, 3.4, 4.5, 4.51, 5.41])) # ceil机制：向上取整

[2. 4. 5. 5. 6.]


In [39]:
print(np.floor([1.2, 3.4, 4.5, 4.51, 5.41])) # floor：向下取整

[1. 3. 4. 4. 5.]


In [40]:
np.isnan([1, np.nan, 3]) # isnan()：检测缺失值(缺失值默认为NaN)

array([False,  True, False])

In [41]:
arr8 = np.random.randint(1, 20, (3, 3))
print(arr8, arr8.dtype, arr8.ndim, arr8.size, sep="\n")

[[13  5 16]
 [15  7 19]
 [ 1  5  1]]
int32
2
9


In [42]:
print(f"求和arr8: {np.sum(arr8)}") # 求和

求和arr8: 82


In [43]:
print(f"求平均arr8: {np.mean(arr8)}") # 求平均

求平均arr8: 9.11111111111111


In [44]:
print(f"中位数arr8: {np.median(arr8)}") # 求中位数：基数个数，排序之后中间的数；偶数个数，排序之后中间两数的平均

中位数arr8: 7.0


## 方差和标准差的统计意义
- 度量离散程度  
  方差/标准差越大，说明数据分布越分散；反之，越集中。  
- 与均值配合  
  仅均值无法反映数据波动，需辅以标准差进行全面描述。  
- 单位与解读  
  标准差具有与原数据相同的单位，更直观。

In [45]:
print(f"标准差arr8: {np.std(arr8)}") # 计算标准差
print(f"方差arr8: {np.var(arr8)}") # 计算标准差

标准差arr8: 6.36735501417529
方差arr8: 40.54320987654321


In [46]:
print(f"arr8:\n {arr8}")
print(f"max arr8: {np.max(arr8)}, 最大值索引: {np.argmax(arr8)}") # 获取一个数组的最大值，并获取它的索引
print(f"min arr8: {np.min(arr8)},最小值索引: {np.argmin(arr8)}") # 获取一个数组的最小值，并获取它的索引

arr8:
 [[13  5 16]
 [15  7 19]
 [ 1  5  1]]
max arr8: 19, 最大值索引: 5
min arr8: 1,最小值索引: 6


In [47]:
print(f"百分比取出数据：{np.percentile(arr8, 20)}") # numpy.percentile(arr, percent)，percent是百分制，0~100

百分比取出数据：3.4000000000000004


In [75]:
print(f"arr8:\n {arr8}")
print(np.cumsum(arr8)) # 累计和，自第一项起，前n项的和，返回对象为list
print(np.cumprod(arr8)) # 累计乘积，自第一项起，前n项的乘积，返回对象为list

arr8:
 [[13  5 16]
 [15  7 19]
 [ 1  5  1]]
[13 18 34 49 56 75 76 81 82]
[      13       65     1040    15600   109200  2074800  2074800 10374000
 10374000]


In [76]:
arr9 = np.random.randint(1,20, [3, 3])
print(arr9)

[[18  9 14]
 [11 18  5]
 [19  9 15]]


In [77]:
print(f"arr8: \n{arr8}")
print(f"arr9: \n{arr9}")
# numpy.greater(arr, num)，该函数返回一个bool元素列表，其中True和False表示的是arr数组中的元素是否 **大于** num
print(f"np.greater(arr8, 10): \n{np.greater(arr8, 10)}")
print(f"np.greater(arr8, arr9): \n{np.greater(arr8, arr9)}") # 两个数组之间元素逐一比较

arr8: 
[[13  5 16]
 [15  7 19]
 [ 1  5  1]]
arr9: 
[[18  9 14]
 [11 18  5]
 [19  9 15]]
np.greater(arr8, 10): 
[[ True False  True]
 [ True False  True]
 [False False False]]
np.greater(arr8, arr9): 
[[False False  True]
 [ True False  True]
 [False False False]]


In [78]:
print(f"arr8: \n{arr8}")
print(f"arr9: \n{arr9}")
# numpy.less(arr, num)，该函数返回一个bool元素列表，其中True和False表示的是arr数组中的元素是否 **小于** num
print(f"np.less(arr8, 10): \n{np.less(arr8, 10)}")
print(f"np.less(arr8, arr9:\n {np.less(arr8, arr9)}") # 两个数组之间元素逐一比较

arr8: 
[[13  5 16]
 [15  7 19]
 [ 1  5  1]]
arr9: 
[[18  9 14]
 [11 18  5]
 [19  9 15]]
np.less(arr8, 10): 
[[False  True False]
 [False  True False]
 [ True  True  True]]
np.less(arr8, arr9:
 [[ True  True False]
 [False  True False]
 [ True  True  True]]


In [52]:
print(f"arr8: \n{arr8}")
print(f"arr9: \n{arr9}")
print(f"p.equal(arr8, 19): \n{np.equal(arr8, 19)}") # numpy.equal(arr, num)，该函数返回一个bool元素列表，其中True和False表示的是arr数组中的元素是否 **等于** num
print(f"p.equal(arr8, arr9): \n{np.equal(arr8, arr9)}") # 两个数组之间元素逐一比较

arr8: 
[[13  5 16]
 [15  7 19]
 [ 1  5  1]]
arr9: 
[[ 5 19  2]
 [ 8  2  2]
 [ 6  9  2]]
p.equal(arr8, 19): 
[[False False False]
 [False False  True]
 [False False False]]
p.equal(arr8, arr9): 
[[False False False]
 [False False False]
 [False False False]]


In [53]:
print("logical_and: ", np.logical_and([1, 0, 1], [0, 1, 1])) # 两个数组之间元素逐一做与运算
print("logical_or: ", np.logical_or([1, 0, 1], [0, 1, 1])) # 两个数组之间元素逐一做或运算
print("logical_not: ", np.logical_not([1, 0, 1])) # 两个数组之间元素逐一做非运算

logical_and:  [False False  True]
logical_or:  [ True  True  True]
logical_not:  [False  True False]


In [54]:
print(np.any([0,0,0,0])) # 检查数组中是否有元素为真
print(np.any([0,0,0,1]))

False
True


In [55]:
print(f"arr8: \n{arr8}")
print("arr8<10: \n", np.where(arr8<10, arr8, -1)) # np.where(条件，满足条件的元素从哪里取， 不满足条件的元素从哪里取)
print("arr8<10: \n", np.where(arr8<10, 1, -1)) # 例：在数组arr8中，满足arr8<3的元素返回1，不满足返回-1
print(np.where(
    arr8<8, "小于8",
    np.where(arr8>15, "大于15", "8~15") # 条件可以嵌套使用，将目标元素进行多分类
))

arr8: 
[[13  5 16]
 [15  7 19]
 [ 1  5  1]]
arr8<10: 
 [[-1  5 -1]
 [-1  7 -1]
 [ 1  5  1]]
arr8<10: 
 [[-1  1 -1]
 [-1  1 -1]
 [ 1  1  1]]
[['8~15' '小于8' '大于15']
 ['8~15' '小于8' '大于15']
 ['小于8' '小于8' '小于8']]


In [56]:
 # np.select([条件数组]，[结论数组]，default用于处理意外情况)，注意：条件数组中的某些联合条件需要使用&|！等符号连接

np.select([arr8 < 8, (8 <= arr8) & (arr8<= 15), arr8 > 15],["小于8", "8~15", "大于15"], default="?")

array([['8~15', '小于8', '大于15'],
       ['8~15', '小于8', '大于15'],
       ['小于8', '小于8', '小于8']], dtype='<U4')

In [57]:
np.random.seed(100)
arr9 = np.random.randint(1, 100, 20)
print("排序前：")
print(f"arr9: {arr9}")
print("排序后：")
arr9.sort() # 原地排序，直接在原数组中改变值
print(f"arr9: {arr9}")

arr10 = np.random.randint(1, 100, 20)
print("排序前：")
print(f"arr10: {arr10}")
print("排序后：")
print(f"arr10: {np.sort(arr10)}") # 非原地排序，不改变原有数据值

排序前：
arr9: [ 9 25 68 88 80 49 11 95 53 99 54 67 99 15 35 25 16 61 59 17]
排序后：
arr9: [ 9 11 15 16 17 25 25 35 49 53 54 59 61 67 68 80 88 95 99 99]
排序前：
arr10: [10 94 87  3 28  5 32  2 14 84  5 92 60 68  8 50 48 66 62 15]
排序后：
arr10: [ 2  3  5  5  8 10 14 15 28 32 48 50 60 62 66 68 84 87 92 94]


In [61]:
np.random.seed(100)
arr10 = np.random.randint(1, 10, 20)
print(f"去重前： \n {arr10}")
newarr10 = np.unique(arr10) # 去重函数
print(f"去重后： \n {newarr10}")

去重前： 
 [9 9 4 8 8 1 5 3 6 3 3 3 2 1 9 5 1 7 3 5]
去重后： 
 [1 2 3 4 5 6 7 8 9]


In [64]:
np.random.seed(100)
arr11 = np.random.randint(1, 10, 5)
arr12 = np.random.randint(1, 10, 5)
print(f"arr11: {arr11}")
print(f"arr12: {arr12}")
newarr = np.concat((arr11, arr12)) # 拼接函数：直接将数组进行拼接
print(f"拼接之后： \n {newarr}")

arr11: [9 9 4 8 8]
arr12: [1 5 3 6 3]
拼接之后： 
 [9 9 4 8 8 1 5 3 6 3]


In [66]:
arr13 = np.random.randint(1, 20, 20)
print(f"分割前：\n{arr13}")

print(np.split(arr13, [1, 5, 15])) # 分割函数：numpy.split(待分割数组， 需要分割的位置（是位置而不是索引）)

分割前：
[16  2 15  8 17  3 10  3 15 18 17 16  8 14  7 13 19  1  3 11]
[array([16], dtype=int32), array([ 2, 15,  8, 17], dtype=int32), array([ 3, 10,  3, 15, 18, 17, 16,  8, 14,  7], dtype=int32), array([13, 19,  1,  3, 11], dtype=int32)]


In [73]:
print(f"arr13.shape: {arr13.shape}")
print(np.reshape(arr13, (2, 10))) # 数组形状调整函数，用于重塑数组的形状，重塑后的形状必须能恰好容纳原有的数据的个数

arr13.shape: (20,)
[[16  2 15  8 17  3 10  3 15 18]
 [17 16  8 14  7 13 19  1  3 11]]
