## 本章为`numpy`的复习与练习章节

# 题目 1：温度数据分析

某城市一周的最高气温（℃）为 \([28, 30, 29, 31, 32, 30, 29]\)。

- 计算平均气温、最高气温和最低气温。
- 找出气温超过 \(30℃\) 的天数。

In [1]:
import numpy as np

list1 = np.array([28, 30, 29, 31, 32, 30, 29])

max_c = np.max(list1)
print(f"最高气温： {max_c}")

min_c = np.min(list1)
print(f"最低气温： {min_c}")

mean_c = np.mean(list1)
print(f"平均气温： {np.round(mean_c, 2)}")

# 通过np.where()函数，设计条件判断出气温高于30℃和低于30℃的部分，并分别将其赋值为1和0，对最终的数组求和
days = np.where(list1 > 30, 1, 0) 
print(f"气温超过30℃的天数： {np.sum(days)}")

最高气温： 32
最低气温： 28
平均气温： 29.86
气温超过30℃的天数： 2


# 题目 2：学生成绩统计

某班级 5 名学生的数学成绩为 \([85, 90, 78, 92, 88]\)。

- 计算成绩的平均分、中位数和标准差。

In [2]:
import numpy as np

list1 = np.array([85, 90, 78, 92, 88])

mean_score = np.mean(list1)
print(f"平均成绩：{mean_score}")

mid_score = np.median(list1)
print(f"成绩中位数：{mid_score}")

std = np.std(list1)
print(f"成绩标准差：{np.round(std, 3)}")

平均成绩：86.6
成绩中位数：88.0
成绩标准差：4.883


# 题目 3：矩阵运算

给定矩阵 \( A = [[1, 2], [3, 4]] \) 和 \( B = [[5, 6], [7, 8]] \)。

- 计算 \( A + B \) 和 \( A * B \)（逐元素乘法）。
- 计算 \( A \) 和 \( B \) 的矩阵乘法（点积）。

In [3]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

sum_AB = A + B
print(f"(A+B): \n{sum_AB}")

acc_AB = A * B
print(f"(A*B): \n{acc_AB}")

dot_AB = A @ B
print(f"(A@B): \n{dot_AB}")

(A+B): 
[[ 6  8]
 [10 12]]
(A*B): 
[[ 5 12]
 [21 32]]
(A@B): 
[[19 22]
 [43 50]]


# 题目 4：随机数据生成

生成一个 (3, 4) 的随机整数数组，范围 [0, 10)。

- 计算每列的最大值和每行的最小值。
- 将数组中的所有奇数替换为 -1。

In [4]:
import numpy as np
np.random.seed(200)

arr = np.random.randint(0, 10, (3, 4))
print(f"arr:\n{arr}")

line_max = np.max(arr, axis=0)
print(f"每一列的最大值： {line_max}")

row_max = np.max(arr, axis=1)
print(f"每一行的最大值： {row_max}")

new = np.where(arr%2!=0, -1, arr)
print(f"将数组中的所有奇数替换为-1之后：\n{new}")

arr:
[[9 0 4 7]
 [9 9 9 6]
 [8 1 7 3]]
每一列的最大值： [9 9 9 7]
每一行的最大值： [9 9 8]
将数组中的所有奇数替换为-1之后：
[[-1  0  4 -1]
 [-1 -1 -1  6]
 [ 8 -1 -1 -1]]


# 题目 5：数组变形

创建一个 1 到 12 的一维数组，并转换为 \( (3, 4) \) 的二维数组。

- 计算每行的和与每列的平均值。
- 将数组还原，重新展开为一维数组。

In [5]:
import numpy as np

arr = np.arange(1, 13)
print(f"arr: {arr}")

arr = np.reshape(arr, (3, 4))
print(f"reshape之后的arr: \n{arr}")

aver_col = np.mean(arr, axis=0)
print(f"每列的均值： {aver_col}")

aver_row = np.sum(arr, axis=1)
print(f"每行的和： {aver_row}")

arr = np.reshape(arr, [12, ])
print(f"展平的arr: {arr}")


arr: [ 1  2  3  4  5  6  7  8  9 10 11 12]
reshape之后的arr: 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
每列的均值： [5. 6. 7. 8.]
每行的和： [10 26 42]
展平的arr: [ 1  2  3  4  5  6  7  8  9 10 11 12]


# 生成一个 (5, 5) 的随机数组，范围 [0, 20)

- 找出数组中大于 10 的元素
- 将所有大于 10 的元素替换为 0

In [6]:
import numpy as np
np.random.seed(200)

arr = np.random.randint(0,20, (5, 5))
print(f"arr: \n{arr}")

print("所有大于10的元素：\n", np.where(arr>10, arr, 0))
print("所有大于10的元素：\n", arr>10)

print("将所有大于10的元素替换成0：\n", np.where(arr>10, 0, arr))

arr: 
[[ 9 16  4 10 12]
 [15 14 11  6 10]
 [ 1  7 19  9 15]
 [ 1 14  7 13 16]
 [19 10  6  3  0]]
所有大于10的元素：
 [[ 0 16  0  0 12]
 [15 14 11  0  0]
 [ 0  0 19  0 15]
 [ 0 14  0 13 16]
 [19  0  0  0  0]]
所有大于10的元素：
 [[False  True False False  True]
 [ True  True  True False False]
 [False False  True False  True]
 [False  True False  True  True]
 [ True False False False False]]
将所有大于10的元素替换成0：
 [[ 9  0  4 10  0]
 [ 0  0  0  6 10]
 [ 1  7  0  9  0]
 [ 1  0  7  0  0]
 [ 0 10  6  3  0]]


# 题目 7：统计函数应用

某公司 6 个月的销售额（万元）为 \([120, 135, 110, 125, 130, 140]\)。

- 计算销售额的总和、均值和方差。
- 找出销售额最高的月份和最低的月份。

In [7]:
import numpy as np

arr = np.array([120, 135, 110, 125, 130, 140])

sum_ = np.sum(arr)
print(f"总和是：{sum_}")

mean_ = np.mean(arr)
print(f"均值是：{np.round(mean_, 3)}")

var_ = np.var(arr)
print(f"方差是：{np.round(var_, 3)}")

max_mon = np.argmax(arr)
print(f"销售额最高的月是：{max_mon+1} 月")

min_mon = np.argmin(arr)
print(f"销售额最低的月是：{min_mon+1} 月")

总和是：760
均值是：126.667
方差是：97.222
销售额最高的月是：6 月
销售额最低的月是：3 月


# 题目 8：数组拼接

给定 \( A = [1, 2, 3] \) 和 \( B = [4, 5, 6] \)。

- 将 \( A \) 和 \( B \) 水平拼接为一个新数组
- 将 \( A \) 和 \( B \) 垂直拼接为一个新数组

In [21]:
import numpy as np

A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

C = np.concatenate([A, B])
print("水平拼接：\n", C)

print("垂直拼接：\n", np.reshape(C, (2, 3))) # 直接对形状进行重构

水平拼接：
 [1 2 3 4 5 6]
垂直拼接：
 [[1 2 3]
 [4 5 6]]


# 题目 9：唯一值与排序

给定数组 \([2, 1, 2, 3, 1, 4, 3]\)。

- 找出数组中的唯一值并排序
- 计算每个唯一值出现的次数

In [26]:
import numpy as np

arr = np.array([2, 1, 2, 3, 1, 4, 3])

new_arr, counts = np.unique(arr, return_counts=True)

print(f"唯一值：{new_arr}")
print(f"每个唯一值出现的次数：{counts}") # 次数对应唯一值数组new_arr



唯一值：[1 2 3 4]
每个唯一值出现的次数：[2 2 2 1]


# 题目 10：综合应用

某商店 5 天的销售额（万元）和成本（万元）如下：

销售额：\[ 20, 25, 22, 30, 28 \]

成本：\[ 15, 18, 16, 22, 20 \]

- 计算每天的利润（销售额 - 成本）
- 计算利润的平均值和标准差
- 找出利润最高的天数

In [39]:
import numpy as np

xiaoshou = np.array([20, 25, 22, 30, 28])
chengben = np.array([15, 18, 16, 22, 20])

lirun = xiaoshou - chengben
print(f"每天的利润为：{lirun}")

aver = np.mean(lirun)
std = np.std(lirun)
print(f"利润的平均值：{aver}；标准差：{std}")

# 法一
ind = np.argmax(lirun)
days = np.where(
    lirun==lirun[ind],
    1,
    0
)
print(f"利润最高的天数为 {sum(days)} 天")

# 法二
cnt = len(lirun[lirun==np.max(lirun)])
print(f"利润最高的天数为 {cnt} 天")

每天的利润为：[5 7 6 8 8]
利润的平均值：6.8；标准差：1.16619037896906
利润最高的天数为 2 天
利润最高的天数为 2 天
